library(RCy3)
cytoscapePing ()
commandsHelp('bridgedb')
commandsHelp('bridgedb id mapping')
commandsHelp('bridgedb get id types')
commandsHelp('bridgedb resource list')
#cytoscapePing(base.url = "127.0.0.1:1234")
#cytoscapeVersionInfo ()
